# Übung zu NumPy und pandas

Hier sind einige Aufgaben für dich, um das aufzufrischen, was du in den Notebooks zuvor gesehen hast.

Es wird dir helfen, die **Lernziele** aus dem vorherigen Notebook zu festigen. Du solltest in der Lage sein
- NumPy arrays zu erstellen
- sie mit grundlegenden mathematischen Operatoren zu manipulieren
- Zeilen, Spalten und Elemente durch Indizierung zu extrahieren
- Aggregationsmethoden (wie sum, min, max, std) auf NumPy arrays zu verwenden

## Teil 1: NumPy arrays erstellen.

1. Bitte erstelle ein NumPy array aus der Liste:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Bitte erstelle ein numpy array, das die Werte von 1 bis 10 enthält.
- Bitte erstelle ein numpy array von 0 bis 5 mit einer Schrittweite von 0,2
- Erstelle ein numpy array mit der Form 2,3 mit Zufallswerten

In [1]:
import numpy as np

my_list = [1, 2, 5, 6, 8]
np.array(my_list)

array([1, 2, 5, 6, 8])

2. Bitte erstelle ein NumPy array, das die Werte von 1 bis 10 enthält.

In [2]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Bitte erstelle ein NumPy array von 0 bis 5 mit einer Schrittweite von 0,2

In [4]:
np.arange(0, 5.1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

4. Erstelle ein NumPy array mit der Form 2,3 mit Zufallswerten

In [3]:
np.random.random((2, 3))

array([[0.99831864, 0.67315891, 0.35071075],
       [0.59555456, 0.4605035 , 0.82815882]])

## Teil 2: NumPy arrays manipulieren.

1. Bitte erstelle ein NumPy array mit (1, 3, '4', 7, 12, '0'). Definiere den Inhalt als Integer.

In [6]:
arr = np.array((1, 3, '4', 7, 12, '0'), dtype=int)
arr

array([ 1,  3,  4,  7, 12,  0])

2. Überprüfe den Datentyp der Objekte und die Form des Arrays

In [7]:
arr.dtype, arr.shape

(dtype('int64'), (6,))

3. Aktualisiere den 4. Wert auf 30.

In [8]:
arr[3] = 30
arr

array([ 1,  3,  4, 30, 12,  0])

4. Forme das Array in eine 2x3-Matrix um.

In [9]:
matrix = arr.reshape(2, 3)
matrix

array([[ 1,  3,  4],
       [30, 12,  0]])

5. Bitte addiere 8 zu jedem Wert in der ersten Zeile und 12 zu jedem in der zweiten Zeile.

In [ ]:
matrix = matrix + np.array([[8], [12]])
matrix

6. Multipliziere die erste Spalte mit 2, die zweite mit 3 und die dritte mit 4.

In [ ]:
matrix = matrix * np.array([2, 3, 4])
matrix

7. Bitte summiere alle Zahlen in der ersten Zeile und alle Zahlen in der zweiten Zeile.

In [ ]:
matrix.sum(axis=1)

8. Suche ähnlich die größte Zahl für jede Spalte.

In [ ]:
matrix.max(axis=0)

9. Extrahiere die Zahl in der zweiten Spalte und der ersten Zeile.

In [ ]:
matrix[0, 1]

10. Überprüfe, bei welchem Index der Wert genau 48 ist.

In [ ]:
np.argwhere(matrix == 48)